-- ============================================================================
-- Affinity Solutions DCR + ML Demo — Data Loading
-- Run AFTER 01_environment.sql
-- 
-- This script:
--   1. Uploads CSV files from data/ folder to the DATA_STAGE
--   2. Creates tables and loads data from CSVs
--
-- IMPORTANT: Before running this script, upload data files to the stage.
-- From the repo root, run the upload script:
--   ./setup/upload_data.sh
-- ============================================================================

USE DATABASE AFFINITY_DEMO;
USE WAREHOUSE AFFINITY_GEN_WH;

-- ============================================================================
-- MATCH RATE SUMMARY (the key view used by all dashboards)
-- We load it as a table since the underlying crosswalk views aren't needed
-- ============================================================================
USE SCHEMA CLEANROOM;

CREATE OR REPLACE TABLE MATCH_RATE_SUMMARY (
  PLATFORM VARCHAR, MATCH_CODE VARCHAR, MATCH_LEVEL VARCHAR,
  WATERFALL_STEP NUMBER, MATCHED_COUNT NUMBER, HH_ONLY_COUNT NUMBER,
  PCT_OF_MATCHED FLOAT, PCT_OF_TOTAL_AFS FLOAT
);
COPY INTO MATCH_RATE_SUMMARY FROM @AFFINITY_DEMO.APPS.DATA_STAGE/cleanroom/match_rate_summary.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE MATCH_METHOD_ORDER (
  METHOD_CODE VARCHAR, DEFAULT_ORDER NUMBER, MATCH_LEVEL VARCHAR, 
  DESCRIPTION VARCHAR, APPLICABLE_PLATFORMS VARCHAR
);
COPY INTO MATCH_METHOD_ORDER FROM @AFFINITY_DEMO.APPS.DATA_STAGE/cleanroom/match_method_order.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE CROSSWALK_TTD (
  AFS_INDID VARCHAR, AFS_HHID VARCHAR, CLIENT_AFS_INDID VARCHAR, CLIENT_AFS_HHID VARCHAR,
  MATCH_CODE VARCHAR, MATCH_LEVEL VARCHAR, RETURN_CODE VARCHAR, WATERFALL_STEP NUMBER,
  MATCH_DESCRIPTION VARCHAR, PLATFORM VARCHAR, CLIENT_INDID VARCHAR, MATCH_TIMESTAMP TIMESTAMP_LTZ
);
COPY INTO CROSSWALK_TTD FROM @AFFINITY_DEMO.APPS.DATA_STAGE/cleanroom/crosswalk_ttd.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE CROSSWALK_PUBMATIC LIKE CROSSWALK_TTD;
COPY INTO CROSSWALK_PUBMATIC FROM @AFFINITY_DEMO.APPS.DATA_STAGE/cleanroom/crosswalk_pubmatic.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE CROSSWALK_KARGO LIKE CROSSWALK_TTD;
COPY INTO CROSSWALK_KARGO FROM @AFFINITY_DEMO.APPS.DATA_STAGE/cleanroom/crosswalk_kargo.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE GROUND_TRUTH_TTD (
  INDID VARCHAR, HHID VARCHAR, CRM_ID VARCHAR, ASSIGNED_MATCH_CODE VARCHAR, ASSIGNED_MATCH_LEVEL VARCHAR
);
COPY INTO GROUND_TRUTH_TTD FROM @AFFINITY_DEMO.APPS.DATA_STAGE/cleanroom/ground_truth_ttd.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE GROUND_TRUTH_PUBMATIC (
  INDID VARCHAR, HHID VARCHAR, PUBMATIC_USER_ID VARCHAR, ASSIGNED_MATCH_CODE VARCHAR, ASSIGNED_MATCH_LEVEL VARCHAR
);
COPY INTO GROUND_TRUTH_PUBMATIC FROM @AFFINITY_DEMO.APPS.DATA_STAGE/cleanroom/ground_truth_pubmatic.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE GROUND_TRUTH_KARGO (
  INDID VARCHAR, HHID VARCHAR, KARGO_USER_ID VARCHAR, ASSIGNED_MATCH_CODE VARCHAR, ASSIGNED_MATCH_LEVEL VARCHAR
);
COPY INTO GROUND_TRUTH_KARGO FROM @AFFINITY_DEMO.APPS.DATA_STAGE/cleanroom/ground_truth_kargo.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- ============================================================================
-- ML SCHEMA — Model registry, validation, rules, delivery
-- ============================================================================
USE SCHEMA ML;

CREATE OR REPLACE TABLE MODEL_REGISTRY (
  MODEL_NAME VARCHAR(100), MODEL_TYPE VARCHAR(100), SCHEMA_LOCATION VARCHAR(100),
  DESCRIPTION VARCHAR(500), TARGET_TYPE VARCHAR(100), TRAINING_DATA VARCHAR(200),
  FEATURES VARCHAR(500), KEY_METRIC VARCHAR(500), CREATED_AT TIMESTAMP_LTZ
);
COPY INTO MODEL_REGISTRY FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/model_registry.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE PROPENSITY_DRIVERS (
  DIM_NAME VARCHAR, DIM_VALUE VARCHAR, PROPENSITY_MULTIPLIER FLOAT, RATIONALE VARCHAR
);
COPY INTO PROPENSITY_DRIVERS FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/propensity_drivers.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE BIDDING_RULES (
  RULE_ID NUMBER, PREDICATE VARCHAR, DIM VARCHAR, DIM_VALUE VARCHAR, SUPPORT NUMBER,
  PURCHASE_RATE FLOAT, BASELINE_RATE FLOAT, RAW_LIFT FLOAT, SHRUNK_LIFT FLOAT,
  BID_MULTIPLIER FLOAT, CI_LOWER FLOAT, CI_UPPER FLOAT, RULE_ACTION VARCHAR,
  SOURCE_PLATFORM VARCHAR, VALID_FROM DATE, VALID_TO DATE
);
COPY INTO BIDDING_RULES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/bidding_rules.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- TTD validation tables
CREATE OR REPLACE TABLE MODEL_VALIDATION_PURCHASE_DECILES (
  DECILE NUMBER, IMPRESSIONS NUMBER, ACTUAL_PURCHASES NUMBER, PURCHASE_RATE_PCT FLOAT,
  AVG_MODEL_PROB_PCT FLOAT, CUMUL_PURCHASES NUMBER, CUMUL_CAPTURE_PCT NUMBER, DECILE_LIFT FLOAT
);
COPY INTO MODEL_VALIDATION_PURCHASE_DECILES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/model_validation_purchase_deciles.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE MODEL_VALIDATION_FEATURE_IMPORTANCE (
  MODEL VARCHAR, RANK NUMBER, FEATURE VARCHAR, IMPORTANCE_SCORE FLOAT
);
COPY INTO MODEL_VALIDATION_FEATURE_IMPORTANCE FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/model_validation_feature_importance.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE MODEL_VALIDATION_PURCHASE_CONFUSION (
  THRESHOLD NUMBER, TRUE_POS NUMBER, TRUE_NEG NUMBER, FALSE_POS NUMBER,
  FALSE_NEG NUMBER, PRECISION_PCT NUMBER, RECALL_PCT NUMBER
);
COPY INTO MODEL_VALIDATION_PURCHASE_CONFUSION FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/model_validation_purchase_confusion.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE VALIDATION_HOLDOUT_RESULTS (
  IS_HOLDOUT NUMBER, SET_NAME VARCHAR, IMPRESSIONS NUMBER, PURCHASES NUMBER,
  PURCHASE_RATE_PCT FLOAT, AVG_COST FLOAT, TOTAL_PURCHASE_VALUE FLOAT,
  COST_PER_PURCHASE FLOAT, ROAS FLOAT
);
COPY INTO VALIDATION_HOLDOUT_RESULTS FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/validation_holdout_results.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- PubMatic validation tables
CREATE OR REPLACE TABLE PUBMATIC_VALIDATION_DECILES (
  DECILE NUMBER, TOTAL NUMBER, PURCHASERS NUMBER, PURCHASE_RATE_PCT FLOAT,
  PCT_OF_ALL_PURCHASES FLOAT, CUMUL_CAPTURE_PCT NUMBER, DECILE_LIFT FLOAT
);
COPY INTO PUBMATIC_VALIDATION_DECILES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/pubmatic_validation_deciles.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE PUBMATIC_FEATURE_IMPORTANCE (
  MODEL VARCHAR, RANK NUMBER, FEATURE VARCHAR, IMPORTANCE_SCORE FLOAT
);
COPY INTO PUBMATIC_FEATURE_IMPORTANCE FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/pubmatic_feature_importance.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE PUBMATIC_HOLDOUT_RESULTS (
  SET_NAME VARCHAR, IMPRESSIONS NUMBER, PURCHASES NUMBER,
  PURCHASE_RATE_PCT FLOAT, COST_PER_PURCHASE FLOAT, ROAS FLOAT
);
COPY INTO PUBMATIC_HOLDOUT_RESULTS FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/pubmatic_holdout_results.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- Kargo validation tables
CREATE OR REPLACE TABLE KARGO_VALIDATION_DECILES LIKE PUBMATIC_VALIDATION_DECILES;
COPY INTO KARGO_VALIDATION_DECILES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/kargo_validation_deciles.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE KARGO_FEATURE_IMPORTANCE LIKE PUBMATIC_FEATURE_IMPORTANCE;
COPY INTO KARGO_FEATURE_IMPORTANCE FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/kargo_feature_importance.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE KARGO_HOLDOUT_RESULTS (
  SET_NAME VARCHAR, IMPRESSIONS NUMBER, PURCHASES NUMBER, PURCHASE_RATE_PCT FLOAT
);
COPY INTO KARGO_HOLDOUT_RESULTS FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/kargo_holdout_results.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- Delivery tables
CREATE OR REPLACE TABLE DELIVERY_AUDIENCE_MULTIPLIER (
  SEGMENT_TIER VARCHAR, QUADRANT VARCHAR, AUDIENCE_SIZE NUMBER,
  TIER_MULTIPLIER FLOAT, AVG_PROPENSITY FLOAT, AVG_PREDICTED_SPEND FLOAT
);
COPY INTO DELIVERY_AUDIENCE_MULTIPLIER FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/delivery_audience_multiplier.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DELIVERY_PER_ID_INSTRUCTION (
  ADDRESSABLE_ID VARCHAR, BRAND_ID NUMBER, QUADRANT VARCHAR, BID_MULTIPLIER FLOAT,
  PROPENSITY_TIER VARCHAR, PREDICTED_SPEND_30D FLOAT, PROPENSITY_SCORE FLOAT,
  REFRESH_DATE DATE, EXPIRY_DATE DATE
);
COPY INTO DELIVERY_PER_ID_INSTRUCTION FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/delivery_per_id_instruction.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DELIVERY_VALUE_BASED_BIDDING (
  ADDRESSABLE_ID VARCHAR, BRAND_ID NUMBER, BRAND_NAME VARCHAR, PREDICTED_SPEND_30D FLOAT,
  BID_VALUE_CEILING FLOAT, EXPECTED_REVENUE FLOAT, QUADRANT VARCHAR, PROPENSITY_TIER VARCHAR
);
COPY INTO DELIVERY_VALUE_BASED_BIDDING FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/delivery_value_based_bidding.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE ACCURACY_PROOF (
  INDID VARCHAR, BRAND_ID NUMBER, PREDICTED_SPEND_30D FLOAT, PROPENSITY_SCORE FLOAT,
  PROPENSITY_TIER VARCHAR, PERCENTILE_RANK FLOAT, ACTUAL_SPEND NUMBER,
  ACTUAL_TX_COUNT NUMBER, DID_PURCHASE NUMBER, DOLLAR_ERROR_PCT FLOAT
);
COPY INTO ACCURACY_PROOF FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/accuracy_proof.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- ============================================================================
-- AI SCHEMA — Quadrant strategy
-- ============================================================================
USE SCHEMA AI;

CREATE OR REPLACE TABLE QUADRANT_SUMMARY_V (
  QUADRANT VARCHAR, AUDIENCE_SIZE NUMBER, AVG_MULTIPLIER FLOAT,
  AVG_PREDICTED_SPEND FLOAT, AVG_PRIOR_SPEND FLOAT, STRATEGIC_OBJECTIVE VARCHAR
);
COPY INTO QUADRANT_SUMMARY_V FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/quadrant_summary.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- ============================================================================
-- AFS_PROVIDER — Prediction feed (the main Affinity data table for dashboards)
-- ============================================================================
USE SCHEMA AFS_PROVIDER;

CREATE OR REPLACE TABLE PREDICTION_FEED_V (
  INDID VARCHAR, HHID VARCHAR, BRAND_ID NUMBER, PREDICTED_SPEND_30D FLOAT,
  PREDICTION_DATE DATE, PERCENTILE_RANK FLOAT, CONFIDENCE_SCORE FLOAT,
  PROPENSITY_SCORE FLOAT, PROPENSITY_TIER VARCHAR, PROPENSITY_DATE DATE,
  SPEND_PREDICTION_DATE DATE
);
COPY INTO PREDICTION_FEED_V FROM @AFFINITY_DEMO.APPS.DATA_STAGE/afs_provider/prediction_feed_v.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- ============================================================================
-- TTD_CONSUMER — Demo output tables
-- ============================================================================
USE SCHEMA TTD_CONSUMER;

CREATE OR REPLACE TABLE DEMO_OUTPUT_CONVERSION_ENRICHMENT (
  IMPRESSIONID VARCHAR, BRAND_ID NUMBER, BRAND_NAME VARCHAR, PURCHASE_AMOUNT FLOAT,
  TX_COUNT NUMBER, PURCHASE_MONTH DATE, MATCH_CODE VARCHAR, MATCH_LEVEL VARCHAR
);
COPY INTO DEMO_OUTPUT_CONVERSION_ENRICHMENT FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ttd_consumer/demo_output_conversion_enrichment.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DEMO_OUTPUT_BIDDING_RULES (
  RULE_ID NUMBER, PREDICATE_TTD VARCHAR, BID_MULTIPLIER FLOAT, SUPPORT NUMBER,
  RAW_LIFT FLOAT, SHRUNK_LIFT FLOAT, RULE_ACTION VARCHAR, CI_LOWER FLOAT, CI_UPPER FLOAT,
  VALID_FROM DATE, VALID_TO DATE, FIELD_NAMESPACE VARCHAR
);
COPY INTO DEMO_OUTPUT_BIDDING_RULES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ttd_consumer/demo_output_bidding_rules.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DEMO_OUTPUT_PREDICTION_MULTIPLIERS (
  CLIENT_ID VARCHAR, BRAND_ID NUMBER, BRAND_NAME VARCHAR, QUADRANT VARCHAR,
  BID_MULTIPLIER FLOAT, PREDICTED_SPEND_30D FLOAT, PROPENSITY_SCORE FLOAT,
  PROPENSITY_TIER VARCHAR, STRATEGIC_OBJECTIVE VARCHAR
);
COPY INTO DEMO_OUTPUT_PREDICTION_MULTIPLIERS FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ttd_consumer/demo_output_prediction_multipliers.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- ============================================================================
-- PUBMATIC_CONSUMER — Demo output tables
-- ============================================================================
USE SCHEMA PUBMATIC_CONSUMER;

CREATE OR REPLACE TABLE DEMO_OUTPUT_INVENTORY_YIELD_SCORES (
  SITE_DOMAIN VARCHAR, AD_FORMAT VARCHAR, DEVICE_TYPE_LABEL VARCHAR, GEO_DMA VARCHAR,
  CONTENT_GENRE VARCHAR, IMPRESSIONS NUMBER, PURCHASES NUMBER, PURCHASE_RATE NUMBER,
  YIELD_MULTIPLIER NUMBER, SUPPORT NUMBER
);
COPY INTO DEMO_OUTPUT_INVENTORY_YIELD_SCORES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/pubmatic_consumer/demo_output_inventory_yield_scores.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DEMO_OUTPUT_FLOOR_RECOMMENDATIONS (
  SEGMENT_ID NUMBER, DIMENSIONS VARCHAR, BASELINE_FLOOR NUMBER, RECOMMENDED_FLOOR NUMBER,
  EXPECTED_REVENUE_LIFT_PCT NUMBER, IMPRESSIONS NUMBER, YIELD_MULTIPLIER NUMBER
);
COPY INTO DEMO_OUTPUT_FLOOR_RECOMMENDATIONS FROM @AFFINITY_DEMO.APPS.DATA_STAGE/pubmatic_consumer/demo_output_floor_recommendations.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DEMO_OUTPUT_PURCHASE_INVENTORY_PACKAGES (
  PACKAGE_NAME VARCHAR, INCLUDED_DOMAIN VARCHAR, INCLUDED_FORMAT VARCHAR,
  PURCHASE_RATE NUMBER, ESTIMATED_REACH NUMBER
);
COPY INTO DEMO_OUTPUT_PURCHASE_INVENTORY_PACKAGES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/pubmatic_consumer/demo_output_purchase_inventory_packages.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DEMO_OUTPUT_SSP_BIDDING_RULES (
  RULE_ID NUMBER, PREDICATE VARCHAR, DIM VARCHAR, DIM_VALUE VARCHAR, SUPPORT NUMBER,
  PURCHASE_RATE FLOAT, BASELINE_RATE FLOAT, RAW_LIFT FLOAT, SHRUNK_LIFT FLOAT,
  BID_MULTIPLIER FLOAT, CI_LOWER FLOAT, CI_UPPER FLOAT, RULE_ACTION VARCHAR,
  SOURCE_PLATFORM VARCHAR, VALID_FROM DATE, VALID_TO DATE
);
COPY INTO DEMO_OUTPUT_SSP_BIDDING_RULES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/pubmatic_consumer/demo_output_ssp_bidding_rules.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DEMO_OUTPUT_PUBLISHER_MULTIPLIERS (
  PUBLISHER VARCHAR, AD_FORMAT VARCHAR, DEVICE_TYPE NUMBER, GEO_METRO VARCHAR,
  IMPRESSIONS NUMBER, PURCHASES NUMBER, PURCHASE_RATE_PCT FLOAT, YIELD_MULTIPLIER FLOAT,
  BID_MULTIPLIER FLOAT, FLOOR_TIER VARCHAR
);
COPY INTO DEMO_OUTPUT_PUBLISHER_MULTIPLIERS FROM @AFFINITY_DEMO.APPS.DATA_STAGE/pubmatic_consumer/demo_output_publisher_multipliers.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DEMO_OUTPUT_MATCH_SUMMARY (
  PLATFORM VARCHAR, MATCH_CODE VARCHAR, MATCH_LEVEL VARCHAR, WATERFALL_STEP NUMBER,
  MATCHED_COUNT NUMBER, HH_ONLY_COUNT NUMBER, PCT_OF_MATCHED FLOAT, PCT_OF_TOTAL_AFS FLOAT
);
COPY INTO DEMO_OUTPUT_MATCH_SUMMARY FROM @AFFINITY_DEMO.APPS.DATA_STAGE/pubmatic_consumer/demo_output_match_summary.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- ============================================================================
-- KARGO_CONSUMER — Demo output tables
-- ============================================================================
USE SCHEMA KARGO_CONSUMER;

CREATE OR REPLACE TABLE DEMO_OUTPUT_PLACEMENT_PURCHASE_SCORES (
  PLACEMENT_NAME VARCHAR, CREATIVE_FORMAT VARCHAR, TOTAL_EVENTS NUMBER,
  BRANDS_PURCHASED NUMBER, TOTAL_PURCHASE_VALUE FLOAT, AVG_PURCHASE_VALUE FLOAT
);
COPY INTO DEMO_OUTPUT_PLACEMENT_PURCHASE_SCORES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/kargo_consumer/demo_output_placement_purchase_scores.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DEMO_OUTPUT_CTV_ATTRIBUTION (
  DEVICE_PLATFORM VARCHAR, APP_NAME VARCHAR, EVENTS NUMBER, VIDEO_COMPLETIONS NUMBER,
  BRANDS_PURCHASED NUMBER, TOTAL_PURCHASE_VALUE FLOAT, AVG_PURCHASE_VALUE FLOAT
);
COPY INTO DEMO_OUTPUT_CTV_ATTRIBUTION FROM @AFFINITY_DEMO.APPS.DATA_STAGE/kargo_consumer/demo_output_ctv_attribution.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DEMO_OUTPUT_ENGAGEMENT_PURCHASE_ATTR (
  AUCTION_ID VARCHAR, EVENT_TYPE VARCHAR, PUBLISHER_DOMAIN VARCHAR, CREATIVE_FORMAT VARCHAR,
  PLACEMENT_NAME VARCHAR, DEVICE_TYPE VARCHAR, DEVICE_PLATFORM VARCHAR, APP_NAME VARCHAR,
  BRAND_ID NUMBER, BRAND_NAME VARCHAR, PURCHASE_AMOUNT FLOAT, MATCH_CODE VARCHAR
);
COPY INTO DEMO_OUTPUT_ENGAGEMENT_PURCHASE_ATTR FROM @AFFINITY_DEMO.APPS.DATA_STAGE/kargo_consumer/demo_output_engagement_purchase_attr.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DEMO_OUTPUT_ENGAGEMENT_QUALITY_RULES (
  RULE_ID NUMBER, PREDICATE VARCHAR, SUPPORT NUMBER, AVG_PURCHASE FLOAT, LIFT FLOAT
);
COPY INTO DEMO_OUTPUT_ENGAGEMENT_QUALITY_RULES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/kargo_consumer/demo_output_engagement_quality_rules.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE DEMO_OUTPUT_ML_ENGAGEMENT_RULES (
  RULE_ID NUMBER, PREDICATE VARCHAR, DIM VARCHAR, DIM_VALUE VARCHAR, SUPPORT NUMBER,
  PURCHASE_RATE FLOAT, BASELINE_RATE FLOAT, RAW_LIFT FLOAT, SHRUNK_LIFT FLOAT,
  BID_MULTIPLIER FLOAT, CI_LOWER FLOAT, CI_UPPER FLOAT, RULE_ACTION VARCHAR,
  SOURCE_PLATFORM VARCHAR, VALID_FROM DATE, VALID_TO DATE
);
COPY INTO DEMO_OUTPUT_ML_ENGAGEMENT_RULES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/kargo_consumer/demo_output_ml_engagement_rules.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- ============================================================================
-- ADROLL_CONSUMER — AdRoll demo output tables
-- ============================================================================
USE SCHEMA ADROLL_CONSUMER;

CREATE OR REPLACE TABLE ADROLL_FUNNEL_PURCHASE_RULES (
  RULE_ID NUMBER, PREDICATE VARCHAR, DIM VARCHAR, DIM_VALUE VARCHAR, SUPPORT NUMBER,
  PURCHASE_RATE FLOAT, BASELINE_RATE FLOAT, RAW_LIFT FLOAT, SHRUNK_LIFT FLOAT,
  BID_MULTIPLIER FLOAT, CI_LOWER FLOAT, CI_UPPER FLOAT, RULE_ACTION VARCHAR,
  SOURCE_PLATFORM VARCHAR, VALID_FROM DATE, VALID_TO DATE
);
COPY INTO ADROLL_FUNNEL_PURCHASE_RULES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/adroll_consumer/adroll_funnel_purchase_rules.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE ADROLL_CHANNEL_ATTRIBUTION (
  CHANNEL VARCHAR, CONVERSIONS NUMBER, PIXEL_REVENUE NUMBER, CARD_SWIPE_REVENUE NUMBER,
  REVENUE_DELTA_PCT FLOAT, VERIFIED_PURCHASES NUMBER, TRUE_PURCHASE_RATE_PCT FLOAT
);
COPY INTO ADROLL_CHANNEL_ATTRIBUTION FROM @AFFINITY_DEMO.APPS.DATA_STAGE/adroll_consumer/adroll_channel_attribution.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE ADROLL_CTV_ATTRIBUTION (
  CAMPAIGN_NAME VARCHAR, VIDEO_IMPRESSIONS NUMBER, VIDEO_COMPLETIONS NUMBER,
  CTV_SPEND NUMBER, MATCHED_PURCHASERS NUMBER, TOTAL_PURCHASE_VALUE NUMBER,
  CTV_ROAS FLOAT, COMPLETION_TO_PURCHASE_RATE FLOAT
);
COPY INTO ADROLL_CTV_ATTRIBUTION FROM @AFFINITY_DEMO.APPS.DATA_STAGE/adroll_consumer/adroll_ctv_attribution.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE ADROLL_AUDIENCE_SEGMENTS (
  SEGMENT_EID VARCHAR, SEGMENT_NAME VARCHAR, SEGMENT_TYPE VARCHAR,
  DURATION NUMBER, IS_CONVERSION BOOLEAN, CONVERSION_VALUE FLOAT, ESTIMATED_SIZE NUMBER
);
COPY INTO ADROLL_AUDIENCE_SEGMENTS FROM @AFFINITY_DEMO.APPS.DATA_STAGE/adroll_consumer/adroll_audience_segments.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- ============================================================================
-- ADROLL_B2B — B2B firmographics and account scores
-- ============================================================================
USE SCHEMA ADROLL_B2B;

CREATE OR REPLACE TABLE ADROLL_SITE_TRAFFIC_REVEALER (
  DOMAIN VARCHAR, COMPANY_NAME VARCHAR, COMPANY_INDUSTRY VARCHAR,
  COMPANY_REVENUE VARCHAR, COMPANY_SIZE VARCHAR, JOURNEY_STAGE VARCHAR,
  FIRST_VISIT_DATE DATE, TOTAL_VISITS NUMBER, TOTAL_VISITORS NUMBER,
  CONTACT_EMAIL_SHA256 VARCHAR
);
COPY INTO ADROLL_SITE_TRAFFIC_REVEALER FROM @AFFINITY_DEMO.APPS.DATA_STAGE/adroll_b2b/adroll_site_traffic_revealer.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE ADROLL_ACCOUNT_SCORES (
  DOMAIN VARCHAR, COMPANY_NAME VARCHAR, COMPANY_INDUSTRY VARCHAR,
  COMPANY_REVENUE VARCHAR, COMPANY_SIZE VARCHAR, JOURNEY_STAGE VARCHAR,
  TOTAL_VISITS NUMBER, TOTAL_VISITORS NUMBER, PURCHASE_SCORE FLOAT,
  PREDICTED_ACCOUNT_VALUE NUMBER, SCORE_TIER VARCHAR
);
COPY INTO ADROLL_ACCOUNT_SCORES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/adroll_b2b/adroll_account_scores.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- ============================================================================
-- CLEANROOM — AdRoll crosswalk and match data
-- ============================================================================
USE SCHEMA CLEANROOM;

CREATE OR REPLACE TABLE ADROLL_MATCH_RATE_SUMMARY (
  PLATFORM VARCHAR, MATCH_CODE VARCHAR, MATCH_LEVEL VARCHAR,
  WATERFALL_STEP NUMBER, MATCHED_COUNT NUMBER, HH_ONLY_COUNT NUMBER,
  PCT_OF_MATCHED FLOAT, PCT_OF_TOTAL_AFS FLOAT
);
COPY INTO ADROLL_MATCH_RATE_SUMMARY FROM @AFFINITY_DEMO.APPS.DATA_STAGE/cleanroom/adroll_match_rate_summary.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE CROSSWALK_ADROLL LIKE CROSSWALK_TTD;
COPY INTO CROSSWALK_ADROLL FROM @AFFINITY_DEMO.APPS.DATA_STAGE/cleanroom/crosswalk_adroll.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE GROUND_TRUTH_ADROLL (
  INDID VARCHAR, HHID VARCHAR, ADROLL_EMAIL_SHA256 VARCHAR,
  ASSIGNED_MATCH_CODE VARCHAR, ASSIGNED_MATCH_LEVEL VARCHAR
);
COPY INTO GROUND_TRUTH_ADROLL FROM @AFFINITY_DEMO.APPS.DATA_STAGE/cleanroom/ground_truth_adroll.csv.gz FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- ============================================================================
-- ML — AdRoll validation tables
-- ============================================================================
USE SCHEMA ML;

CREATE OR REPLACE TABLE ADROLL_CONVERSION_DECILES (
  DECILE NUMBER, TOTAL NUMBER, PURCHASERS NUMBER, PURCHASE_RATE_PCT FLOAT,
  PCT_OF_ALL_PURCHASES FLOAT, CUMUL_CAPTURE_PCT NUMBER, DECILE_LIFT FLOAT
);
COPY INTO ADROLL_CONVERSION_DECILES FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/adroll_conversion_deciles.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE ADROLL_FEATURE_IMPORTANCE (
  MODEL VARCHAR, RANK NUMBER, FEATURE VARCHAR, IMPORTANCE_SCORE FLOAT
);
COPY INTO ADROLL_FEATURE_IMPORTANCE FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/adroll_feature_importance.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

CREATE OR REPLACE TABLE ADROLL_HOLDOUT_RESULTS (
  SET_NAME VARCHAR, CONVERSIONS NUMBER, PURCHASES NUMBER,
  PURCHASE_RATE_PCT FLOAT, PIXEL_REVENUE NUMBER, CARD_SWIPE_REVENUE NUMBER
);
COPY INTO ADROLL_HOLDOUT_RESULTS FROM @AFFINITY_DEMO.APPS.DATA_STAGE/ml/adroll_holdout_results.csv FILE_FORMAT = AFFINITY_DEMO.APPS.CSV_FORMAT;

-- ============================================================================
-- Verification
-- ============================================================================
SELECT 'Data loading complete. Verifying row counts...' AS STATUS;

SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT
FROM AFFINITY_DEMO.INFORMATION_SCHEMA.TABLES
WHERE ROW_COUNT > 0 AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_SCHEMA, TABLE_NAME;
